### PR TITLE
Added URIs to Instagram and LinkedIn profiles in footer.yml file.

### PR DESCRIPTION
**Pull request by csengineer1990**
I have added the URIs for the Instagram and LinkedIn profiles in the footer.yml file. Please review the changes and let me know if there's anything else I need to update.

### CODE REVIEW

**Comment by csengineer1990** [comment]
Could you please add or label this issue with 'hacktoberfest' and 'hacktoberfest-accepted'?

**Review by ctubbsii — COMMENTED** [review]
Thank you for your PR. However, this data file is tightly coupled to the specific version of the theme, so it shouldn't be updated by itself, without updating the entire theme. The links to NSA's current social media presences can be found on the main website, www.nsa.gov

**Comment by ctubbsii** [comment]
I'll try to test these changes by themselves to see if the current theme supports these. If not, I will close this PR (relates to #58)

**Comment by ctubbsii** [comment]
I just double checked, and it looks like I am correct that just like #58, this won't work without updating the theme.

**Pull request closed without merging**
